## Numpy

- Array from numpy

# Array

- An array is a collection of homogenous data-type.(single data type)
- 4 bytes
- Array can store data very compactly and more efficient for storing large amount of data.
- Array are great for numerical operations,list cannot directly handle math operations
- As the array size increase ,numpy array get around 30 times faster than python list.
- Because the numpy array is denely packed in memory due to homogeous type,also frees the memory faster.
- you have to explicity import numpy to use array

## List

- whwras list is a collection of hetrogeneous data-type
- 14 byte
- list less efficient than array for storing large amount of data.
- it is python data type

In [2]:
import numpy as np

In [3]:
my_list=["ram",123,50.5,7+2j]
print(my_list)
type(my_list)

['ram', 123, 50.5, (7+2j)]


list

In [6]:
my_array=["ram",123,50.5,7+2j]
print(my_array)
type(my_array)

['ram', 123, 50.5, (7+2j)]


list

In [8]:
my_array=np.array(["ram",123,50.5,7+2j])

print(my_array)
type(my_array)

['ram' '123' '50.5' '(7+2j)']


numpy.ndarray

In [9]:
my_array=np.array([123,50.5,7+2j])
print(my_array)
type(my_array)

[123. +0.j  50.5+0.j   7. +2.j]


numpy.ndarray

In [10]:
my_array=np.array([123,50.5])
print(my_array)
type(my_array)

[123.   50.5]


numpy.ndarray

string>complex>float>int

### Empty  Numpy array

In [12]:
import numpy as np

In [13]:
a=np.array([])
a

array([], dtype=float64)

In [15]:
my_array=np.array([[123,50.5],[1,2]])
print(my_array)
type(my_array)

[[123.   50.5]
 [  1.    2. ]]


numpy.ndarray

In [16]:
my_array.ndim

2

## 1.ndim   # check dimention

In [17]:
my_array.ndim

2

In [18]:
a=np.array([1,2,34])
print(a)
print("the dim is:",a.ndim)

[ 1  2 34]
the dim is: 1


In [19]:
a=np.array([[[1,2,34],[1,2,3]]])
print(a)
print("the dim is:",a.ndim)

[[[ 1  2 34]
  [ 1  2  3]]]
the dim is: 3


In [21]:
a=np.array([[[1,2,34],[1,2,3],[1,2,34],[1,2,3]]])
print(a)
print("the dim is:",a.ndim)

[[[ 1  2 34]
  [ 1  2  3]
  [ 1  2 34]
  [ 1  2  3]]]
the dim is: 3


## 2.dtype

In [23]:
a=np.array([[1,2,34],[1,2,3]],dtype=str)
print(a)
print("the dim is",a.ndim)

[['1' '2' '34']
 ['1' '2' '3']]
the dim is 2


In [24]:
a=np.array([[1,2,34],[1,2,3]],dtype=float)
print(a)
print("the dim is",a.ndim)

[[ 1.  2. 34.]
 [ 1.  2.  3.]]
the dim is 2


In [25]:
a=np.array([[1,2,34],[1,2,3]],dtype=complex)
print(a)
print("the dim is",a.ndim)

[[ 1.+0.j  2.+0.j 34.+0.j]
 [ 1.+0.j  2.+0.j  3.+0.j]]
the dim is 2


In [26]:
a=np.array([[1,2,34],[1,2,3]],dtype=int)
print(a)
print("the dim is",a.ndim)

[[ 1  2 34]
 [ 1  2  3]]
the dim is 2


In [27]:
a=np.array([[5,2,34.3],[1,2,3]])
print(a)
print("the dim is:",a.ndim)

[[ 5.   2.  34.3]
 [ 1.   2.   3. ]]
the dim is: 2


In [28]:
a.dtype

dtype('float64')

### 3.iteamsize

In [30]:
a.itemsize

8

## 4.shape

In [31]:
a.shape

(2, 3)

## 5.size

In [32]:
a.size

6

## 6.Data

In [33]:
a.data

## indexing and slicing

In [34]:
a=np.array([[5,2,34],[1,2,3]])

In [35]:
a.ndim

2

In [36]:
a[0][0]

5

In [38]:
a[0][2]

34

In [39]:
a[1][0]

1

In [42]:
a=np.array([[[1,2,3,4,5,6],[11,22,33,44,55,66]],[[111,222,333,444,555,666],[1111,2222,3333,4444,5555,6666]]])
print(a)
a.ndim

[[[   1    2    3    4    5    6]
  [  11   22   33   44   55   66]]

 [[ 111  222  333  444  555  666]
  [1111 2222 3333 4444 5555 6666]]]


3

In [43]:
a[0]

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [44]:
a[0][0]

array([1, 2, 3, 4, 5, 6])

In [45]:
a[0][1]

array([11, 22, 33, 44, 55, 66])

In [46]:
a[1][1][-1]

6666

In [47]:
a[1:,1:,-1:]

array([[[6666]]])

In [48]:
a=np.array([[[1,2,3,4,5,6],[11,22,33,44,55,66]],[[111,222,333,444,555,666],[1111,2222,3333,4444,5555,6666]]])
print(a)
a.ndim

[[[   1    2    3    4    5    6]
  [  11   22   33   44   55   66]]

 [[ 111  222  333  444  555  666]
  [1111 2222 3333 4444 5555 6666]]]


3

In [49]:
a[0:1,0:1,1:3]

array([[[2, 3]]])

In [50]:
a=np.array([[[1,2,3,4,5,6]]])
print(a)
a.ndim

[[[1 2 3 4 5 6]]]


3

In [51]:
a[0][0][-1]

6

### Creating Randome numbers

In [52]:
np.random.rand(5)

array([0.79743676, 0.4042442 , 0.95569591, 0.01806233, 0.26346297])

In [53]:
np.random.rand(4,5)

array([[0.47326432, 0.81932228, 0.5859867 , 0.14616429, 0.93782113],
       [0.52847836, 0.44310774, 0.90736235, 0.82020886, 0.75201079],
       [0.28194781, 0.62907047, 0.18059623, 0.50502316, 0.60361699],
       [0.38369202, 0.29698014, 0.87509425, 0.33842021, 0.54483096]])

### numpy functions()

In [ ]:
numpy.linspace:create an array with evenly spaced values over a specified range.
numpy.logspace:create an array with evenly spaced values on a logarithmic scale,   


## 1.array()

In [54]:
a=np.array([[5,2,34.3],[1,2,3]])
a

array([[ 5. ,  2. , 34.3],
       [ 1. ,  2. ,  3. ]])

In [55]:
np.zeros((9,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [56]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

## 3.ones()

In [57]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [58]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

## 4.empty()

In [60]:
np.empty([])

array(1.)

## 5.arange()

In [61]:
np.arange(1,20,2)        # same like in for loop


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## 6.linespace()

In [63]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

## 7.logspace

- Return number spaced evenly on a log scale
- LOG-Base10

In [71]:
np.logspace(1,100)

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

# Manipulation function

In [73]:
a=np.array([[5,2,24.3],[1,2,3]])
a

array([[ 5. ,  2. , 24.3],
       [ 1. ,  2. ,  3. ]])

## reshape()

In [74]:
a=np.random.randint(1,10,(5,10))
a

array([[2, 8, 7, 3, 3, 1, 9, 7, 1, 3],
       [8, 4, 6, 1, 1, 1, 2, 1, 3, 3],
       [4, 9, 6, 8, 1, 3, 5, 8, 7, 2],
       [9, 3, 1, 1, 8, 1, 6, 6, 1, 4],
       [7, 8, 1, 4, 9, 6, 6, 5, 6, 6]])

In [75]:
b=a.reshape(25,2)

In [76]:
b

array([[2, 8],
       [7, 3],
       [3, 1],
       [9, 7],
       [1, 3],
       [8, 4],
       [6, 1],
       [1, 1],
       [2, 1],
       [3, 3],
       [4, 9],
       [6, 8],
       [1, 3],
       [5, 8],
       [7, 2],
       [9, 3],
       [1, 1],
       [8, 1],
       [6, 6],
       [1, 4],
       [7, 8],
       [1, 4],
       [9, 6],
       [6, 5],
       [6, 6]])

### 2 Transpose

In [2]:
import numpy as np        

In [3]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
y.transpose()   # row ro col and col to row

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 3. Concatination

In [7]:
a=np.array([[5,2,24.3],[1,2,3]])
a

array([[ 5. ,  2. , 24.3],
       [ 1. ,  2. ,  3. ]])

In [10]:
np.concatenate(a)

array([ 5. ,  2. , 24.3,  1. ,  2. ,  3. ])

In [11]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
np.concatenate(y)

array([1, 2, 3, 4, 5, 6, 7, 8])

## vstact()

In [14]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.vstack(y)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Hstack

In [17]:
a=np.array([[5,2,24.3],[1,2,3]])
np.hstack(a)

array([ 5. ,  2. , 24.3,  1. ,  2. ,  3. ])

### Random

In [18]:
a=np.random.rand(4,4,4)
print(a)
a.ndim

[[[0.08809326 0.73161391 0.85298195 0.29069972]
  [0.75618406 0.00602076 0.12385555 0.48061709]
  [0.4818984  0.6854544  0.33059543 0.45081934]
  [0.60080307 0.71982464 0.82909393 0.54637376]]

 [[0.25479828 0.09274053 0.04730419 0.31815958]
  [0.01910915 0.55066361 0.68255416 0.17235412]
  [0.50728115 0.57083825 0.55215656 0.76181392]
  [0.69595659 0.01407956 0.26781441 0.09115317]]

 [[0.97745334 0.76459642 0.24137304 0.62054091]
  [0.10071092 0.87765461 0.2726249  0.18239474]
  [0.45346391 0.82273223 0.6611262  0.75032357]
  [0.57470844 0.1227266  0.13916425 0.64884114]]

 [[0.37705206 0.80437188 0.94489872 0.3723973 ]
  [0.59684925 0.03974677 0.39218654 0.7668624 ]
  [0.26179393 0.93834747 0.75790487 0.81401572]
  [0.74485184 0.20792131 0.45383118 0.70621156]]]


3

In [19]:
np.random.randint(1,10,(2,3))

array([[5, 8, 4],
       [1, 9, 1]])

In [20]:
x=np.random.randint(1,10,(6,6))       #36=(2,18),(3,12),(12,3)
x

array([[9, 9, 9, 9, 3, 2],
       [1, 5, 4, 2, 5, 3],
       [6, 4, 7, 7, 5, 9],
       [9, 7, 1, 6, 6, 4],
       [7, 2, 6, 4, 5, 4],
       [3, 5, 3, 8, 1, 8]])

### Full

- Return a new array of given shape and type ,filled with filll_value

In [21]:
np.full((5,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [22]:
a=np.full((4,8),"ms")
a

array([['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms'],
       ['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms'],
       ['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms'],
       ['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms']], dtype='<U2')

In [23]:
np.full_like(a,15)

array([['15', '15', '15', '15', '15', '15', '15', '15'],
       ['15', '15', '15', '15', '15', '15', '15', '15'],
       ['15', '15', '15', '15', '15', '15', '15', '15'],
       ['15', '15', '15', '15', '15', '15', '15', '15']], dtype='<U2')

### eye

- Return  a 2-D array with ones on the diagonal and zero elsewhere

In [24]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [25]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [26]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.eye(5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.eye(10,k=-2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

### Where

In [29]:
z=np.arange(3,50)
z

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
np.where(z<15)
#it give position of that element with satisfy the condition

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),)

In [31]:
np.where(z%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45], dtype=int64),)

In [32]:
np.where(z==6)

(array([3], dtype=int64),)

### Split

- split an array into multiple sub-array

In [34]:
e=np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.split(e,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [36]:
np.split(e,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [37]:
a,b=np.split(e,2)

In [38]:
a

array([0, 1, 2, 3, 4])

### Arithmatic Operation in numpy

In [39]:
import numpy as np

In [40]:
a=np.array([[1,2,10],[5,7,8]])
b=np.array([[10,20,7],[50,70,7]])

In [41]:
a

array([[ 1,  2, 10],
       [ 5,  7,  8]])

In [42]:
b

array([[10, 20,  7],
       [50, 70,  7]])

## add()

In [43]:
a+b    #using operators(+)

array([[11, 22, 17],
       [55, 77, 15]])

In [44]:
np.add(a,b)

array([[11, 22, 17],
       [55, 77, 15]])

### sub()

In [45]:
np.subtract(a,b)

array([[ -9, -18,   3],
       [-45, -63,   1]])

## mult()

In [47]:
np.multiply(a,b)

array([[ 10,  40,  70],
       [250, 490,  56]])

In [48]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[1,2,3],[2,3,4]])

In [49]:
a*b

array([[ 1,  4,  9],
       [ 4,  9, 16]])

In [50]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.mod(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
np.power(a,b)

array([[  1,   4,  27],
       [  4,  27, 256]])

### Statistics

In [53]:
import numpy as np

In [54]:
s=np.array([[50,10,30],[500,100,300],[5,1,3]])
s.ndim

2

In [55]:
s

array([[ 50,  10,  30],
       [500, 100, 300],
       [  5,   1,   3]])

In [56]:
b=np.array([[50,17,4],[50,140,0],[15,1,3]])
b

array([[ 50,  17,   4],
       [ 50, 140,   0],
       [ 15,   1,   3]])

In [57]:
np.amax(b,axis=1)     #0=row , 1=col

array([ 50, 140,  15])

In [58]:
np.amin(s,axis=0)

array([5, 1, 3])

In [59]:
np.amax(s)

500

In [60]:
np.amax(s,axis=0)

array([500, 100, 300])

In [61]:
np.amax(s,axis=1)

array([ 50, 500,   5])

In [62]:
b

array([[ 50,  17,   4],
       [ 50, 140,   0],
       [ 15,   1,   3]])

In [63]:
np.mean(b)

31.11111111111111

In [64]:
(50+50+15+17+140+1+4+3)/9

31.11111111111111

In [65]:
np.var(s)

26960.666666666668

In [66]:
np.std(s)

164.1970361080451

## Datatype

In [67]:
a=np.array([2555])
a.dtype

dtype('int32')

In [68]:
a=np.array([12,2,3,6],dtype=np.float16)

In [69]:
a.dtype

dtype('float16')

In [70]:
a

array([12.,  2.,  3.,  6.], dtype=float16)

In [71]:
np.array(np.datetime64('1999-06-14'))

array('1999-06-14', dtype='datetime64[D]')

In [72]:
new=np.array([1.0,2.0,3.0])
new

array([1., 2., 3.])

In [73]:
b=np.array([1,2,3])

In [74]:
b.astype("str")

array(['1', '2', '3'], dtype='<U11')

In [75]:
b.astype("f")

array([1., 2., 3.], dtype=float32)

In [76]:
np.iinfo(np.int8).max

127

In [77]:
np.iinfo(np.int8).min

-128